'use strict';

module.exports = {
  MARKER_SELECT: "MARKER_SELECT",
  ADD: "MARKER_ADD",
  VIDEO_MARKERS_LOADED: "VIDEO_MARKERS_LOADED",
  VIDEO_MARKER_UPDATED: "VIDEO_MARKER_UPDATED",
  MARKER_HOVER: "MARKER_HOVER",
  MARKER_DELETED: "MARKER_DELETED",
  MARKER_UNSELECT: "MARKER_UNSELECT"
};
