'use strict';

module.exports = {
  SET_PLAYER: "SET_PLAYER",
  SET_TIMESTAMP: "SET_TIMESTAMP",
  SEEK_PLAYER_TO: "SEEK_PLAYER_TO",
  PAUSE_PLAYERS: "PAUSE_PLAYERS",
  PAUSE_PLAYER: "PAUSE_PLAYER"
};
