development: &default
  adapter: postgresql
  database: points_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  user: postgres

test:
  <<: *default
  database: points_test
